### ISSUE TITLE
Can't compile with Ghidra 9.1.2

### ISSUE THREAD

**Issue by Arcnor** [astrelsky/Ghidra-Cpp-Class-Analyzer#20]
Sorry for opening one of "those" issues, but it seems the current `experimental` branch cannot be compiled against 9.1.2?

This is what I'm getting (only the beginning, since it's very long):

```
src/main/java/ghidra/app/cmd/data/rtti/gcc/UnresolvedClassTypeInfoException.java:3: error: cannot find symbol
import ghidra.app.util.demangler.Demangled;
                                ^
  symbol:   class Demangled
  location: package ghidra.app.util.demangler
src/main/java/cppclassanalyzer/data/typeinfo/ArchivedClassTypeInfo.java:20: error: cannot find symbol
import ghidra.app.util.demangler.Demangled;
                                ^
  symbol:   class Demangled
  location: package ghidra.app.util.demangler
src/main/java/cppclassanalyzer/data/typeinfo/ArchivedClassTypeInfo.java:69: error: cannot find symbol
        private final Demangled demangled;
                      ^
  symbol:   class Demangled
  location: class ArchivedClassTypeInfo
src/main/java/cppclassanalyzer/data/typeinfo/ArchivedClassTypeInfo.java:152: error: cannot find symbol
        private static Demangled doDemangle(String symbolName) {
                       ^
  symbol:   class Demangled
  location: class ArchivedClassTypeInfo

...
```

I've run it against a freshly downloaded copy of Ghidra, and I'm using Gradle 6.4 with Java 11 on macOS.

**Comment by astrelsky** [comment]
That is correct. The experimental branch is only compatible with ghidra 9.2 at this time. If you wish to use the plugin with 9.1.2 you must use the [9.1 branch](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/tree/9.1)

https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer#compatibility

**Comment by Arcnor** [comment]
Oh my, really sorry, I read the bottom part of the readme incorrectly, I thought it said 9.1.2 and not 9.2. Really sorry again.

**Comment by astrelsky** [comment]
> Oh my, really sorry, I read the bottom part of the readme incorrectly, I thought it said 9.1.2 and not 9.2. Really sorry again.

No problem.
